name: Deploy Python Lambda Function

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: \${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: \${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          
      - name: Install AWS SAM CLI
        run: |
          pip install aws-sam-cli
      
      - name: Build and deploy with SAM
        run: |
          sam build
          sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name my-python-lambda-api --s3-bucket \${{ secrets.S3_BUCKET }} --capabilities CAPABILITY_IAM
          
      - name: Test Lambda API
        run: |
          ENDPOINT_URL=\$(aws cloudformation describe-stacks --stack-name my-python-lambda-api --query "Stacks[0].Outputs[?OutputKey=='ApiEndpoint'].OutputValue" --output text)
          echo "API Endpoint: \$ENDPOINT_URL"
          curl -s \$ENDPOINT_URL